export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      members: {
        Row: {
          id: string;
          name: string;
          email: string;
          role: string;
          company: string;
          expertise: string;
          can_help_with: string;
          looking_for: string;
          bio: string;
          avatar_url: string | null;
          voice_url: string | null;
          status: string;
          paid: boolean;
          free_requests_used: number;
          created_at: string;
          phone: string | null;
          facebook_url: string | null;
          linkedin_url: string | null;
          company_website: string | null;
          country: string | null;
          open_to_work: boolean;
          job_preferences: string;
          hiring: boolean;
          hiring_preferences: string;
          gender: string | null;
          relationship_status: string | null;
          auth_provider: string | null;
          auth_provider_id: string | null;
          last_login: string | null;
          account_status: string;
          total_requests_count: number;
          requests_today: number;
          abg_class: string | null;
          nickname: string | null;
          display_nickname_in_search: boolean;
          display_nickname_in_match: boolean;
          display_nickname_in_email: boolean;
          discord_username: string | null;
          payment_status: string;
          membership_expiry: string | null;
          approval_status: string;
          is_csv_imported: boolean;
          is_admin: boolean;
          self_description: string | null;
          truth_lie: string | null;
          ideal_day: string | null;
          qualities_looking_for: string | null;
          core_values: string | null;
          deal_breakers: string | null;
          interests: string | null;
          dating_message: string | null;
          other_share: string | null;
          dating_profile_complete: boolean;
          requests_this_month: number;
          month_reset_date: string | null;
          searches_this_month: number;
          search_month_reset_date: string | null;
          public_profile_slug: string | null;
          public_profile_enabled: boolean;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          email: string;
          role?: string;
          company?: string;
          expertise?: string;
          can_help_with?: string;
          looking_for?: string;
          bio?: string;
          avatar_url?: string | null;
          voice_url?: string | null;
          status?: string;
          paid?: boolean;
          free_requests_used?: number;
          created_at?: string;
          phone?: string | null;
          facebook_url?: string | null;
          linkedin_url?: string | null;
          company_website?: string | null;
          country?: string | null;
          open_to_work?: boolean;
          job_preferences?: string;
          hiring?: boolean;
          hiring_preferences?: string;
          gender?: string | null;
          relationship_status?: string | null;
          auth_provider?: string | null;
          auth_provider_id?: string | null;
          last_login?: string | null;
          account_status?: string;
          total_requests_count?: number;
          requests_today?: number;
          abg_class?: string | null;
          nickname?: string | null;
          display_nickname_in_search?: boolean;
          display_nickname_in_match?: boolean;
          display_nickname_in_email?: boolean;
          discord_username?: string | null;
          payment_status?: string;
          membership_expiry?: string | null;
          approval_status?: string;
          is_csv_imported?: boolean;
          is_admin?: boolean;
          self_description?: string | null;
          truth_lie?: string | null;
          ideal_day?: string | null;
          qualities_looking_for?: string | null;
          core_values?: string | null;
          deal_breakers?: string | null;
          interests?: string | null;
          dating_message?: string | null;
          other_share?: string | null;
          dating_profile_complete?: boolean;
          requests_this_month?: number;
          month_reset_date?: string | null;
          searches_this_month?: number;
          search_month_reset_date?: string | null;
          public_profile_slug?: string | null;
          public_profile_enabled?: boolean;
        };
        Update: Partial<Database['public']['Tables']['members']['Insert']>;
        Relationships: [];
      };
      member_references: {
        Row: {
          id: string;
          writer_member_id: string;
          recipient_member_id: string;
          body: string;
          relationship_context: string;
          status: string;
          is_publicly_visible: boolean;
          created_at: string;
          updated_at: string;
          moderated_at: string | null;
          moderated_by_member_id: string | null;
          moderation_note: string | null;
        };
        Insert: {
          id: string;
          writer_member_id: string;
          recipient_member_id: string;
          body: string;
          relationship_context: string;
          status?: string;
          is_publicly_visible?: boolean;
          created_at?: string;
          updated_at?: string;
          moderated_at?: string | null;
          moderated_by_member_id?: string | null;
          moderation_note?: string | null;
        };
        Update: Partial<Database['public']['Tables']['member_references']['Insert']>;
        Relationships: [];
      };
      requests: {
        Row: {
          id: string;
          requester_id: string;
          request_text: string;
          matched_ids: string;
          selected_id: string | null;
          status: string;
          created_at: string;
          category: string | null;
          custom_intro_text: string | null;
        };
        Insert: {
          id: string;
          requester_id: string;
          request_text?: string;
          matched_ids?: string;
          selected_id?: string | null;
          status?: string;
          created_at?: string;
          category?: string | null;
          custom_intro_text?: string | null;
        };
        Update: Partial<Database['public']['Tables']['requests']['Insert']>;
        Relationships: [];
      };
      connections: {
        Row: {
          id: string;
          request_id: string;
          from_id: string;
          to_id: string;
          intro_sent: boolean;
          feedback: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          request_id: string;
          from_id: string;
          to_id: string;
          intro_sent?: boolean;
          feedback?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['connections']['Insert']>;
        Relationships: [];
      };
      request_audits: {
        Row: {
          id: string;
          member_id: string;
          request_id: string | null;
          ip_address: string;
          user_agent: string;
          timestamp: string;
          success: boolean;
          failure_reason: string | null;
          request_type: string;
        };
        Insert: {
          id: string;
          member_id: string;
          request_id?: string | null;
          ip_address?: string;
          user_agent?: string;
          timestamp?: string;
          success?: boolean;
          failure_reason?: string | null;
          request_type?: string;
        };
        Update: Partial<Database['public']['Tables']['request_audits']['Insert']>;
        Relationships: [];
      };
      love_match_requests: {
        Row: {
          id: string;
          request_id: string;
          from_id: string;
          to_id: string;
          status: string;
          from_profile_shared: Json;
          to_profile_shared: Json | null;
          viewed_at: string | null;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          request_id: string;
          from_id: string;
          to_id: string;
          status?: string;
          from_profile_shared?: Json;
          to_profile_shared?: Json | null;
          viewed_at?: string | null;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['love_match_requests']['Insert']>;
        Relationships: [];
      };
      contact_requests: {
        Row: {
          id: string;
          requester_id: string;
          target_id: string;
          message: string;
          status: string;
          feedback: string | null;
          token: string;
          created_at: string;
          responded_at: string | null;
        };
        Insert: {
          id: string;
          requester_id: string;
          target_id: string;
          message?: string;
          status?: string;
          feedback?: string | null;
          token: string;
          created_at?: string;
          responded_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['contact_requests']['Insert']>;
        Relationships: [];
      };
      payment_records: {
        Row: {
          id: string;
          member_id: string;
          amount_vnd: number;
          admin_id: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          member_id: string;
          amount_vnd: number;
          admin_id: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['payment_records']['Insert']>;
        Relationships: [];
      };
      bug_reports: {
        Row: {
          id: string;
          reporter_email: string;
          page_url: string;
          description: string;
          screenshot_url: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id: string;
          reporter_email: string;
          page_url: string;
          description: string;
          screenshot_url?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['bug_reports']['Insert']>;
        Relationships: [];
      };
      news: {
        Row: {
          id: string;
          title: string;
          slug: string;
          category: string;
          excerpt: string;
          content: string;
          image_url: string | null;
          author_name: string;
          published_date: string | null;
          is_published_vi: boolean;
          is_published_en: boolean;
          is_featured: boolean;
          created_at: string;
          title_vi: string | null;
          excerpt_vi: string | null;
          content_vi: string | null;
        };
        Insert: {
          id: string;
          title: string;
          slug: string;
          category?: string;
          excerpt?: string;
          content?: string;
          image_url?: string | null;
          author_name?: string;
          published_date?: string | null;
          is_published_vi?: boolean;
          is_published_en?: boolean;
          is_featured?: boolean;
          created_at?: string;
          title_vi?: string | null;
          excerpt_vi?: string | null;
          content_vi?: string | null;
        };
        Update: Partial<Database['public']['Tables']['news']['Insert']>;
        Relationships: [];
      };
      abg_classes: {
        Row: {
          id: string;
          name: string;
          display_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['abg_classes']['Insert']>;
        Relationships: [];
      };
      community_proposals: {
        Row: {
          id: string;
          created_by_member_id: string;
          title: string;
          description: string;
          category: string;
          status: string;
          is_pinned: boolean;
          commitment_score: number;
          commitment_count: number;
          comment_count: number;
          target_date: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          selected_at: string | null;
          selected_by_member_id: string | null;
          completed_at: string | null;
          admin_note: string | null;
          image_url: string | null;
        };
        Insert: {
          id: string;
          created_by_member_id: string;
          title: string;
          description: string;
          category?: string;
          status?: string;
          is_pinned?: boolean;
          commitment_score?: number;
          commitment_count?: number;
          comment_count?: number;
          target_date?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          selected_at?: string | null;
          selected_by_member_id?: string | null;
          completed_at?: string | null;
          admin_note?: string | null;
          image_url?: string | null;
        };
        Update: Partial<Database['public']['Tables']['community_proposals']['Insert']>;
        Relationships: [];
      };
      community_commitments: {
        Row: {
          id: string;
          proposal_id: string;
          member_id: string;
          commitment_level: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          proposal_id: string;
          member_id: string;
          commitment_level?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['community_commitments']['Insert']>;
        Relationships: [];
      };
      community_proposal_comments: {
        Row: {
          id: string;
          proposal_id: string;
          member_id: string;
          body: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          proposal_id: string;
          member_id: string;
          body: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['community_proposal_comments']['Insert']>;
        Relationships: [];
      };
      community_events: {
        Row: {
          id: string;
          title: string;
          description: string;
          category: string;
          event_mode: string | null;
          event_date: string;
          event_end_date: string | null;
          location: string | null;
          location_url: string | null;
          capacity: number | null;
          capacity_premium: number | null;
          capacity_basic: number | null;
          image_url: string | null;
          created_by_member_id: string;
          organizer_member_id: string | null;
          proposal_id: string | null;
          status: string;
          rsvp_count: number;
          rsvp_score: number;
          comment_count: number;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          completed_at: string | null;
          outcome_summary: string | null;
          fee_premium: number | null;
          fee_basic: number | null;
          fee_guest: number | null;
          capacity_guest: number | null;
          is_public: boolean;
          payment_qr_url: string | null;
          payment_instructions: string | null;
          guest_rsvp_count: number;
        };
        Insert: {
          id: string;
          title: string;
          description: string;
          category?: string;
          event_mode?: string | null;
          event_date: string;
          event_end_date?: string | null;
          location?: string | null;
          location_url?: string | null;
          capacity?: number | null;
          capacity_premium?: number | null;
          capacity_basic?: number | null;
          image_url?: string | null;
          created_by_member_id: string;
          organizer_member_id?: string | null;
          proposal_id?: string | null;
          status?: string;
          rsvp_count?: number;
          rsvp_score?: number;
          comment_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          completed_at?: string | null;
          outcome_summary?: string | null;
          fee_premium?: number | null;
          fee_basic?: number | null;
          fee_guest?: number | null;
          capacity_guest?: number | null;
          is_public?: boolean;
          payment_qr_url?: string | null;
          payment_instructions?: string | null;
          guest_rsvp_count?: number;
        };
        Update: Partial<Database['public']['Tables']['community_events']['Insert']>;
        Relationships: [];
      };
      community_event_rsvps: {
        Row: {
          id: string;
          event_id: string;
          member_id: string;
          commitment_level: string;
          note: string | null;
          actual_attendance: boolean | null;
          actual_participation_score: number | null;
          verified_event_role: string | null;
          attendance_mode: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          event_id: string;
          member_id: string;
          commitment_level?: string;
          note?: string | null;
          actual_attendance?: boolean | null;
          actual_participation_score?: number | null;
          verified_event_role?: string | null;
          attendance_mode?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['community_event_rsvps']['Insert']>;
        Relationships: [];
      };
      community_event_comments: {
        Row: {
          id: string;
          event_id: string;
          member_id: string;
          body: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          event_id: string;
          member_id: string;
          body: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['community_event_comments']['Insert']>;
        Relationships: [];
      };
      event_guest_rsvps: {
        Row: {
          id: string;
          event_id: string;
          guest_name: string;
          guest_email: string;
          guest_phone: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          event_id: string;
          guest_name: string;
          guest_email: string;
          guest_phone?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['event_guest_rsvps']['Insert']>;
        Relationships: [];
      };
      event_payments: {
        Row: {
          id: string;
          event_id: string;
          payer_type: string;
          member_id: string | null;
          guest_rsvp_id: string | null;
          amount_vnd: number;
          status: string;
          confirmed_by_admin_id: string | null;
          payer_name: string;
          payer_email: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          event_id: string;
          payer_type: string;
          member_id?: string | null;
          guest_rsvp_id?: string | null;
          amount_vnd: number;
          status?: string;
          confirmed_by_admin_id?: string | null;
          payer_name: string;
          payer_email: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['event_payments']['Insert']>;
        Relationships: [];
      };
      financial_transactions: {
        Row: {
          id: string;
          type: string;
          category: string;
          amount_vnd: number;
          description: string;
          transaction_date: string;
          event_id: string | null;
          created_by_admin_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          type?: string;
          category: string;
          amount_vnd: number;
          description: string;
          transaction_date: string;
          event_id?: string | null;
          created_by_admin_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['financial_transactions']['Insert']>;
        Relationships: [];
      };
      financial_settings: {
        Row: {
          id: string;
          opening_balance_vnd: number;
          opening_balance_date: string;
          updated_by_admin_id: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          opening_balance_vnd?: number;
          opening_balance_date?: string;
          updated_by_admin_id?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['financial_settings']['Insert']>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
