export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      members: {
        Row: {
          id: string;
          name: string;
          email: string;
          role: string;
          company: string;
          expertise: string;
          can_help_with: string;
          looking_for: string;
          bio: string;
          avatar_url: string | null;
          voice_url: string | null;
          status: string;
          paid: boolean;
          free_requests_used: number;
          created_at: string;
          phone: string | null;
          facebook_url: string | null;
          linkedin_url: string | null;
          company_website: string | null;
          country: string | null;
          open_to_work: boolean;
          job_preferences: string;
          hiring: boolean;
          hiring_preferences: string;
          gender: string | null;
          relationship_status: string | null;
          auth_provider: string | null;
          auth_provider_id: string | null;
          last_login: string | null;
          account_status: string;
          total_requests_count: number;
          requests_today: number;
          abg_class: string | null;
          nickname: string | null;
          display_nickname_in_search: boolean;
          display_nickname_in_match: boolean;
          display_nickname_in_email: boolean;
          discord_username: string | null;
          payment_status: string;
          membership_expiry: string | null;
          approval_status: string;
          is_csv_imported: boolean;
          is_admin: boolean;
          self_description: string | null;
          truth_lie: string | null;
          ideal_day: string | null;
          qualities_looking_for: string | null;
          core_values: string | null;
          deal_breakers: string | null;
          interests: string | null;
          dating_message: string | null;
          other_share: string | null;
          dating_profile_complete: boolean;
          requests_this_month: number;
          month_reset_date: string | null;
          searches_this_month: number;
          search_month_reset_date: string | null;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          email: string;
          role?: string;
          company?: string;
          expertise?: string;
          can_help_with?: string;
          looking_for?: string;
          bio?: string;
          avatar_url?: string | null;
          voice_url?: string | null;
          status?: string;
          paid?: boolean;
          free_requests_used?: number;
          created_at?: string;
          phone?: string | null;
          facebook_url?: string | null;
          linkedin_url?: string | null;
          company_website?: string | null;
          country?: string | null;
          open_to_work?: boolean;
          job_preferences?: string;
          hiring?: boolean;
          hiring_preferences?: string;
          gender?: string | null;
          relationship_status?: string | null;
          auth_provider?: string | null;
          auth_provider_id?: string | null;
          last_login?: string | null;
          account_status?: string;
          total_requests_count?: number;
          requests_today?: number;
          abg_class?: string | null;
          nickname?: string | null;
          display_nickname_in_search?: boolean;
          display_nickname_in_match?: boolean;
          display_nickname_in_email?: boolean;
          discord_username?: string | null;
          payment_status?: string;
          membership_expiry?: string | null;
          approval_status?: string;
          is_csv_imported?: boolean;
          is_admin?: boolean;
          self_description?: string | null;
          truth_lie?: string | null;
          ideal_day?: string | null;
          qualities_looking_for?: string | null;
          core_values?: string | null;
          deal_breakers?: string | null;
          interests?: string | null;
          dating_message?: string | null;
          other_share?: string | null;
          dating_profile_complete?: boolean;
          requests_this_month?: number;
          month_reset_date?: string | null;
          searches_this_month?: number;
          search_month_reset_date?: string | null;
        };
        Update: Partial<Database['public']['Tables']['members']['Insert']>;
        Relationships: [];
      };
      requests: {
        Row: {
          id: string;
          requester_id: string;
          request_text: string;
          matched_ids: string;
          selected_id: string | null;
          status: string;
          created_at: string;
          category: string | null;
          custom_intro_text: string | null;
        };
        Insert: {
          id: string;
          requester_id: string;
          request_text?: string;
          matched_ids?: string;
          selected_id?: string | null;
          status?: string;
          created_at?: string;
          category?: string | null;
          custom_intro_text?: string | null;
        };
        Update: Partial<Database['public']['Tables']['requests']['Insert']>;
        Relationships: [];
      };
      connections: {
        Row: {
          id: string;
          request_id: string;
          from_id: string;
          to_id: string;
          intro_sent: boolean;
          feedback: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          request_id: string;
          from_id: string;
          to_id: string;
          intro_sent?: boolean;
          feedback?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['connections']['Insert']>;
        Relationships: [];
      };
      request_audits: {
        Row: {
          id: string;
          member_id: string;
          request_id: string | null;
          ip_address: string;
          user_agent: string;
          timestamp: string;
          success: boolean;
          failure_reason: string | null;
          request_type: string;
        };
        Insert: {
          id: string;
          member_id: string;
          request_id?: string | null;
          ip_address?: string;
          user_agent?: string;
          timestamp?: string;
          success?: boolean;
          failure_reason?: string | null;
          request_type?: string;
        };
        Update: Partial<Database['public']['Tables']['request_audits']['Insert']>;
        Relationships: [];
      };
      love_match_requests: {
        Row: {
          id: string;
          request_id: string;
          from_id: string;
          to_id: string;
          status: string;
          from_profile_shared: Json;
          to_profile_shared: Json | null;
          viewed_at: string | null;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          request_id: string;
          from_id: string;
          to_id: string;
          status?: string;
          from_profile_shared?: Json;
          to_profile_shared?: Json | null;
          viewed_at?: string | null;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['love_match_requests']['Insert']>;
        Relationships: [];
      };
      contact_requests: {
        Row: {
          id: string;
          requester_id: string;
          target_id: string;
          message: string;
          status: string;
          feedback: string | null;
          token: string;
          created_at: string;
          responded_at: string | null;
        };
        Insert: {
          id: string;
          requester_id: string;
          target_id: string;
          message?: string;
          status?: string;
          feedback?: string | null;
          token: string;
          created_at?: string;
          responded_at?: string | null;
        };
        Update: Partial<Database['public']['Tables']['contact_requests']['Insert']>;
        Relationships: [];
      };
      payment_records: {
        Row: {
          id: string;
          member_id: string;
          amount_vnd: number;
          admin_id: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          member_id: string;
          amount_vnd: number;
          admin_id: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['payment_records']['Insert']>;
        Relationships: [];
      };
      news: {
        Row: {
          id: string;
          title: string;
          slug: string;
          category: string;
          excerpt: string;
          content: string;
          image_url: string | null;
          author_name: string;
          published_date: string | null;
          is_published_vi: boolean;
          is_published_en: boolean;
          is_featured: boolean;
          created_at: string;
          title_vi: string | null;
          excerpt_vi: string | null;
          content_vi: string | null;
        };
        Insert: {
          id: string;
          title: string;
          slug: string;
          category?: string;
          excerpt?: string;
          content?: string;
          image_url?: string | null;
          author_name?: string;
          published_date?: string | null;
          is_published_vi?: boolean;
          is_published_en?: boolean;
          is_featured?: boolean;
          created_at?: string;
          title_vi?: string | null;
          excerpt_vi?: string | null;
          content_vi?: string | null;
        };
        Update: Partial<Database['public']['Tables']['news']['Insert']>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
